pr:
  autoCancel: true
  branches:
    include:
    - '*'
  drafts: true

jobs:
- job: 'Validate_Pull_Request'
  displayName: Validate Pull Request
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        gem install xcpretty slather -N
      failOnStderr: true
  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        find . -name "*.gcda" -print0 | xargs -0 rm
  
  #- task: PythonScript@0
  #  inputs:
  #    scriptSource: 'filePath'
  #    scriptPath: 'build.py'
  #    failOnStderr: true
  - task: Xcode@5
    inputs:
      actions: 'clean build test'
      configuration: 'Debug'
      sdk: 'iphonesimulator'
      xcWorkspacePath: 'MSAL.xcworkspace'
      scheme: 'MSAL (iOS Framework)'
      xcodeVersion: '12'
      packageApp: false
      destinationPlatformOption: 'iOS'
      destinationSimulators: 'iPhone 8,OS=latest'
      publishJUnitResults: true
      testRunTitle: 'test results'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        ./build.py --target iosFramework
      failOnStderr: true
  
  
  