pr:
  autoCancel: true
  branches:
    include:
    - '*'
  drafts: true

jobs:
- job: 'Validate_Pull_Request'
  displayName: Validate Pull Request
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - task: CmdLine@2
    inputs:
      script: 'gem install xcpretty slather -N'
  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        find . -name "*.gcda" -print0 | xargs -0 rm
        set -o pipefail
  #- task: PythonScript@0
  #  inputs:
  #    scriptSource: 'filePath'
  #    scriptPath: 'build.py'
  #    failOnStderr: true
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        { output=$(./build.py 2>&1 1>&3-) ;} 3>&1
        echo "STDERR = ${output}"
      failOnStderr: true
  
  
  