pr:
  autoCancel: true
  branches:
    include:
    - '*'
  drafts: true

jobs:
- job: 'Validate_Pull_Request'
  displayName: Validate Pull Request
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        gem install xcpretty slather -N
      failOnStderr: true
  - checkout: self
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        find . -name "*.gcda" -print0 | xargs -0 rm
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        ./build.py --target iosFramework
        echo "FINAL STATUS = ${FINAL_STATUS}"
      failOnStderr: true
  
  
  